<?php

namespace App\Components\Enum;

enum DepartmentType: string
{
    case MAYOR = 'OFFICE OF THE CITY MAYOR';
    case ADMINISTRATOR = 'OFFICE OF THE CITY ADMINISTRATOR';
    case PLANNING = 'OFFICE OF THE CITY PLANNING AND DEVELOPMENT COORDINATOR';
    case BUDGET = 'OFFICE OF THE CITY BUDGET OFFICER';
    case ACCOUNTANT = 'OFFICE OF THE CITY ACCOUNTANT';
    case GENERAL_SERVICES = 'OFFICE OF THE CITY GENERAL SERVICES OFFICER';
    case LEGAL = 'OFFICE OF THE CITY LEGAL OFFICER';
    case HR = 'OFFICE OF THE CITY HUMAN RESOURCE MANAGEMENT OFFICER';
    case ECONOMIC_ENTERPRISES = 'OFFICE OF THE CITY ECONOMIC ENTERPRISES MANAGER';
    case TREASURER = 'OFFICE OF THE CITY TREASURER';
    case ASSESSOR = 'OFFICE OF THE CITY ASSESSOR';
    case ENGINEER = 'OFFICE OF THE CITY ENGINEER';
    case ARCHITECT = 'OFFICE OF THE CITY ARCHITECT';
    case HEALTH = 'OFFICE OF THE CITY HEALTH OFFICER';
    case SOCIAL_WELFARE = 'OFFICE OF THE CITY SOCIAL WELFARE AND DEVELOPMENT OFFICER';
    case AGRICULTURIST = 'OFFICE OF THE CITY AGRICULTURIST';
    case ENVIRONMENT = 'OFFICE OF THE CITY ENVIRONMENT AND NATURAL RESOURCES OFFICER';
    case VETERINARIAN = 'OFFICE OF THE CITY VETERINARIAN';
    case CIVIL_REGISTRAR = 'OFFICE OF THE CITY CIVIL REGISTRAR';
    case VICE_MAYOR = 'OFFICE OF THE CITY VICE MAYOR';
    case VICE_MAYOR_SP = 'OFFICE OF THE CITY VICE MAYOR / SANGGUNIANG PANLUNGSOD';
    case VICE_MAYOR_LEGISLATIVE = 'OFFICE OF THE CITY VICE MAYOR (SP LEGISLATIVE)';
    case SP = 'OFFICE OF THE SANGGUNIANG PANLUNGSOD';
    case SECRETARY_SP = 'OFFICE OF THE SECRETARY TO THE SANGGUNIAN';
    case DRRMO = 'OFFICE OF THE CITY DISASTER RISK REDUCTION AND MANAGEMENT OFFICER';
    case PESO = 'OFFICE OF THE CITY PUBLIC EMPLOYMENT SERVICES AND CAPABILITY DEVELOPMENT OFFICER';
    case HOUSING = 'OFFICE OF THE CITY HOUSING AND LAND MANAGEMENT OFFICER';
    case TOURISM = 'OFFICE OF THE CITY TOURISM, ARTS, CULTURE AND HERITAGE MANAGEMENT OFFICER';
    case ICT = 'OFFICE OF THE CITY INFORMATION AND COMMUNICATIONS TECHNOLOGY MANAGEMENT OFFICER';


    public static function fromString(string $input): ?self
    {
        // Normalize input: uppercase, strip spaces/underscores/dashes
        $normalized = strtoupper(preg_replace('/[\s_\-]+/', '', $input));

        foreach (self::cases() as $case) {
            $target = strtoupper(preg_replace('/[\s_\-]+/', '', $case->value));
            if ($normalized === $target) {
                return $case;
            }
        }

        return null;
    }
}
